import type { ConversationSentiment, SentimentResult } from "@/lib/types/analysis";
import { tokenize } from "./text-utils";

// AFINN-165 subset: word -> score (-5 to +5)
const AFINN_EN: Record<string, number> = {
  abandon: -2,
  abandoned: -2,
  abuse: -3,
  abused: -3,
  accept: 1,
  accepted: 1,
  accomplish: 2,
  accomplished: 2,
  achievement: 2,
  admire: 3,
  adorable: 3,
  adore: 3,
  advantage: 2,
  afraid: -2,
  aggressive: -2,
  agree: 1,
  alarm: -2,
  amazing: 4,
  amaze: 3,
  amused: 2,
  anger: -3,
  angry: -3,
  annoy: -2,
  annoyed: -2,
  annoying: -2,
  anxiety: -2,
  anxious: -2,
  apologize: -1,
  appalling: -3,
  appreciate: 2,
  approval: 2,
  approve: 2,
  ashamed: -2,
  assault: -3,
  astonish: 2,
  attract: 1,
  attractive: 2,
  awesome: 4,
  awful: -3,
  bad: -3,
  ban: -2,
  bankrupt: -3,
  beautiful: 3,
  benefit: 2,
  best: 3,
  betray: -3,
  better: 2,
  bias: -1,
  bitter: -2,
  blame: -2,
  bless: 2,
  blessing: 3,
  blind: -1,
  bliss: 3,
  block: -1,
  bold: 2,
  bonus: 2,
  bore: -2,
  bored: -2,
  boring: -3,
  brave: 2,
  breakthrough: 3,
  bright: 1,
  brilliant: 4,
  broken: -1,
  brutal: -3,
  bug: -1,
  bully: -3,
  burden: -2,
  calm: 2,
  cancel: -1,
  capable: 2,
  care: 2,
  careful: 2,
  careless: -2,
  celebrate: 3,
  challenge: 1,
  chance: 1,
  chaos: -3,
  charm: 3,
  cheat: -3,
  cheerful: 2,
  clean: 1,
  clear: 1,
  clever: 2,
  collapse: -2,
  comfortable: 2,
  commit: 1,
  compassion: 2,
  compete: 1,
  complain: -2,
  complaint: -2,
  compliment: 2,
  concern: -1,
  confident: 2,
  confuse: -2,
  confused: -2,
  congratulate: 3,
  cool: 1,
  cooperate: 2,
  corrupt: -3,
  courage: 2,
  crash: -2,
  creative: 2,
  crime: -3,
  crisis: -3,
  critical: -2,
  cruel: -3,
  crush: -1,
  cry: -2,
  curious: 1,
  cute: 2,
  damage: -3,
  danger: -2,
  dangerous: -3,
  dare: 1,
  dead: -3,
  death: -3,
  deceive: -3,
  defeat: -2,
  defend: 1,
  delight: 3,
  delightful: 3,
  depress: -3,
  depressed: -3,
  desire: 1,
  despair: -3,
  desperate: -3,
  destroy: -3,
  devastate: -3,
  disappoint: -2,
  disappointed: -2,
  disaster: -3,
  discover: 2,
  disgust: -3,
  dislike: -2,
  dismiss: -1,
  disturb: -2,
  dominate: -1,
  doubt: -1,
  dread: -3,
  dream: 1,
  dull: -2,
  dumb: -3,
  eager: 2,
  easy: 1,
  effective: 2,
  efficient: 2,
  effort: 1,
  elegant: 2,
  embarrass: -2,
  embrace: 1,
  empower: 2,
  encourage: 2,
  enemy: -2,
  engage: 1,
  enjoy: 2,
  enjoyable: 2,
  enormous: 1,
  enrich: 2,
  enthusiasm: 3,
  envious: -2,
  error: -2,
  essential: 1,
  evil: -3,
  excellent: 3,
  excite: 3,
  excited: 3,
  exciting: 3,
  exclusive: 2,
  exhaust: -2,
  expect: 1,
  expensive: -1,
  expert: 2,
  exploit: -2,
  extraordinary: 4,
  extreme: -1,
  fabulous: 4,
  fail: -2,
  failure: -2,
  fair: 2,
  faith: 2,
  fake: -3,
  fame: 1,
  fantastic: 4,
  fascinate: 3,
  fault: -2,
  favor: 2,
  favorite: 2,
  fear: -2,
  fierce: -1,
  fine: 2,
  fix: 1,
  flaw: -2,
  fool: -2,
  forgive: 1,
  fortune: 2,
  free: 2,
  freedom: 2,
  friendly: 2,
  frighten: -2,
  frustrate: -2,
  frustrated: -2,
  fun: 4,
  funny: 3,
  fury: -3,
  generous: 2,
  genius: 3,
  gentle: 2,
  glad: 3,
  gloomy: -2,
  glorious: 3,
  good: 3,
  grace: 2,
  grand: 3,
  grateful: 3,
  great: 3,
  greed: -3,
  grief: -3,
  grim: -2,
  guilty: -2,
  happy: 3,
  harm: -2,
  harmful: -3,
  harsh: -2,
  hate: -4,
  hatred: -4,
  heal: 2,
  healthy: 2,
  heartbreak: -3,
  help: 2,
  helpful: 2,
  hero: 2,
  hesitant: -1,
  honest: 2,
  honor: 2,
  hope: 2,
  hopeful: 2,
  hopeless: -3,
  horrible: -3,
  horror: -3,
  hostile: -3,
  humble: 1,
  humor: 2,
  hurt: -2,
  ideal: 2,
  idiot: -3,
  ignore: -2,
  ill: -2,
  illegal: -3,
  imagine: 1,
  immense: 1,
  impress: 3,
  impressed: 3,
  impressive: 3,
  improve: 2,
  incredible: 4,
  indifferent: -1,
  inferior: -2,
  injustice: -3,
  innocent: 2,
  innovate: 2,
  insane: -2,
  insecure: -2,
  insight: 2,
  inspire: 3,
  inspired: 3,
  insult: -3,
  integrity: 2,
  intelligent: 2,
  interest: 1,
  interested: 2,
  interesting: 2,
  intimidate: -2,
  invincible: 2,
  invite: 1,
  irritate: -3,
  jealous: -2,
  joy: 3,
  joyful: 3,
  justice: 2,
  keen: 1,
  kill: -3,
  kind: 2,
  lack: -2,
  laugh: 2,
  lazy: -2,
  lead: 1,
  learn: 1,
  legend: 2,
  lie: -2,
  lonely: -2,
  lose: -3,
  loss: -3,
  lost: -2,
  love: 3,
  lovely: 3,
  luck: 3,
  lucky: 3,
  mad: -3,
  magic: 2,
  magnificent: 4,
  master: 2,
  mean: -2,
  mercy: 2,
  mess: -2,
  miracle: 4,
  miserable: -3,
  mislead: -3,
  mistake: -2,
  mock: -2,
  modest: 1,
  monster: -2,
  motivate: 2,
  murder: -4,
  nasty: -3,
  neat: 2,
  negative: -2,
  neglect: -2,
  nervous: -2,
  nice: 3,
  nightmare: -3,
  noble: 2,
  odd: -1,
  offend: -2,
  okay: 1,
  opportunity: 2,
  optimistic: 2,
  ordeal: -2,
  outstanding: 5,
  overcome: 2,
  overwhelm: -1,
  pain: -2,
  painful: -2,
  panic: -3,
  paradise: 3,
  passion: 2,
  passionate: 2,
  patience: 2,
  peace: 2,
  peaceful: 2,
  perfect: 3,
  permit: 1,
  pessimistic: -2,
  pity: -1,
  pleasant: 3,
  please: 1,
  pleased: 3,
  pleasure: 3,
  poison: -3,
  polite: 2,
  poor: -2,
  popular: 1,
  positive: 2,
  poverty: -2,
  power: 1,
  powerful: 2,
  praise: 3,
  precious: 2,
  pride: 2,
  privilege: 2,
  problem: -2,
  profit: 2,
  promise: 1,
  promote: 1,
  proud: 2,
  punish: -2,
  pure: 2,
  rage: -3,
  reckless: -2,
  recommend: 2,
  recover: 2,
  refuse: -2,
  regret: -2,
  reject: -2,
  relax: 2,
  relief: 2,
  remarkable: 2,
  rescue: 2,
  resent: -2,
  respect: 2,
  responsible: 1,
  restore: 2,
  revenge: -3,
  reward: 2,
  rich: 2,
  ridiculous: -2,
  risk: -2,
  rude: -2,
  ruin: -3,
  sad: -2,
  safe: 1,
  satisfy: 2,
  save: 2,
  scare: -2,
  secure: 2,
  selfish: -3,
  shame: -2,
  share: 1,
  shock: -2,
  sick: -2,
  silly: -1,
  simple: 1,
  sin: -2,
  sincere: 2,
  smart: 2,
  smile: 2,
  solve: 1,
  sorry: -1,
  special: 2,
  splendid: 3,
  steal: -3,
  strength: 2,
  stress: -2,
  strong: 2,
  struggle: -2,
  stupid: -3,
  succeed: 3,
  success: 3,
  successful: 3,
  suffer: -2,
  superb: 5,
  superior: 2,
  support: 2,
  surprise: 1,
  suspicious: -2,
  sweet: 2,
  talent: 2,
  terrible: -3,
  terrific: 4,
  terror: -3,
  thankful: 2,
  thanks: 2,
  thrill: 3,
  thrive: 3,
  threat: -2,
  tired: -2,
  tolerate: -1,
  top: 2,
  torture: -4,
  tough: -1,
  toxic: -3,
  tragic: -3,
  treasure: 2,
  tremendous: 4,
  triumph: 4,
  trouble: -2,
  true: 2,
  trust: 2,
  ugly: -3,
  unbelievable: 2,
  unfair: -2,
  unfortunate: -2,
  unhappy: -2,
  unique: 2,
  unite: 1,
  upset: -2,
  useful: 2,
  useless: -2,
  vain: -2,
  value: 2,
  victim: -3,
  victory: 3,
  villain: -3,
  violence: -3,
  virtue: 2,
  vital: 2,
  vulnerable: -2,
  warm: 1,
  warn: -1,
  waste: -2,
  weak: -2,
  wealth: 2,
  welcome: 2,
  weird: -1,
  wicked: -2,
  win: 3,
  winner: 3,
  wisdom: 2,
  wise: 2,
  wish: 1,
  wonder: 2,
  wonderful: 4,
  worry: -2,
  worst: -3,
  worth: 2,
  worthless: -3,
  worthy: 2,
  wrong: -2,
  yay: 3,
};

// SentiWS-style German sentiment words
const SENTIWS_DE: Record<string, number> = {
  gut: 3,
  schlecht: -3,
  toll: 3,
  super: 4,
  wunderbar: 4,
  schrecklich: -3,
  furchtbar: -3,
  fantastisch: 4,
  ausgezeichnet: 4,
  hervorragend: 4,
  perfekt: 3,
  liebe: 3,
  hasse: -4,
  freude: 3,
  traurig: -2,
  begeistert: 3,
  nett: 2,
  freundlich: 2,
  gemein: -3,
  dumm: -3,
  klug: 2,
  intelligent: 2,
  interessant: 2,
  langweilig: -2,
  spannend: 2,
  lustig: 3,
  witzig: 2,
  zufrieden: 2,
  unzufrieden: -2,
  dankbar: 2,
  stolz: 2,
  mutig: 2,
  feige: -2,
  ehrlich: 2,
  faul: -2,
  stark: 2,
  schwach: -2,
  reich: 1,
  arm: -2,
  gesund: 2,
  krank: -2,
  frei: 2,
  gefangen: -2,
  sicher: 2,
  friedlich: 2,
  hoffnungsvoll: 2,
  hoffnungslos: -3,
  erfolgreich: 3,
  gescheitert: -2,
  katastrophal: -4,
  angenehm: 2,
  unangenehm: -2,
  positiv: 2,
  negativ: -2,
  lieb: 2,
  grausam: -3,
  prima: 3,
  herrlich: 3,
  elend: -3,
  beeindruckend: 3,
  genial: 4,
  brillant: 4,
  erstaunlich: 3,
  erschreckend: -2,
  faszinierend: 3,
  frustrierend: -2,
  hilfreich: 2,
  hilflos: -2,
  inspirierend: 3,
  irritierend: -2,
  komfortabel: 2,
  chaotisch: -2,
  leidenschaftlich: 2,
  peinlich: -2,
  ruhig: 1,
  stressig: -2,
  talentiert: 2,
  nutzlos: -3,
  verdient: 1,
  verschwendet: -2,
  wertvoll: 2,
  wertlos: -3,
  freundschaft: 2,
  feindschaft: -2,
  absurd: -2,
  bemerkenswert: 2,
  bewundernswert: 3,
  ekelhaft: -3,
  enorm: 1,
  fabelhaft: 4,
  grauenhaft: -3,
  grossartig: 4,
  herausragend: 4,
  miserabel: -3,
  phantastisch: 4,
  prachtvoll: 3,
  scheusslich: -3,
  sensationell: 4,
  traumhaft: 3,
  vorbildlich: 3,
  wundervoll: 4,
  zauberhaft: 3,
};

function scoreTokens(
  tokens: string[],
  lexicon: Record<string, number>,
): { score: number; positive: string[]; negative: string[] } {
  let score = 0;
  const positive: string[] = [];
  const negative: string[] = [];

  for (const token of tokens) {
    const val = lexicon[token];
    if (val !== undefined) {
      score += val;
      if (val > 0) positive.push(token);
      else if (val < 0) negative.push(token);
    }
  }

  return { score, positive, negative };
}

export function analyzeSentiment(text: string, language: "en" | "de" | "mixed"): SentimentResult {
  const tokens = tokenize(text);
  const wordCount = tokens.length || 1;

  if (language === "mixed") {
    const en = scoreTokens(tokens, AFINN_EN);
    const de = scoreTokens(tokens, SENTIWS_DE);
    const totalScore = en.score + de.score;
    return {
      score: totalScore,
      comparative: totalScore / wordCount,
      positive: [...new Set([...en.positive, ...de.positive])],
      negative: [...new Set([...en.negative, ...de.negative])],
    };
  }

  const lexicon = language === "de" ? SENTIWS_DE : AFINN_EN;
  const result = scoreTokens(tokens, lexicon);

  return {
    score: result.score,
    comparative: result.score / wordCount,
    positive: result.positive,
    negative: result.negative,
  };
}

export function analyzeConversationSentiment(
  messages: Array<{ id: string; text: string; sender: string }>,
  language: "en" | "de" | "mixed",
  conversationId: string,
): ConversationSentiment {
  const byMessage: Array<{ messageId: string; score: number }> = [];
  let totalScore = 0;

  for (const msg of messages) {
    const result = analyzeSentiment(msg.text, language);
    byMessage.push({ messageId: msg.id, score: result.comparative });
    totalScore += result.comparative;
  }

  const overall = messages.length > 0 ? totalScore / messages.length : 0;

  return {
    conversationId,
    overall,
    byMessage,
  };
}

export { AFINN_EN, SENTIWS_DE };
